#!/usr/local/bin/php
<?php

// You might need to change the path to your local php interpreter in the first
// line of this file, leaving the hashbang (#!) in place, e.g.:
// #!/usr/bin/php

require_once 'SpinPapiConf.inc.php';

$usage = <<<EOT
spquery -- Command line utility to query SpinPapi
SYNOPSIS
  spcli [-v] method [param value ...]
SpinPapi method specific parameter/value pairs may follow the method argument as 
appropriate according to the SpinPapi API Spec.
See: http://spinitron.com/user-guide/pdf/SpinPapi.pdf
OPTIONS
  -v   Causes more verbose output using var_dump() instead of print_r().
EXAMPLES
  spquery getSong
  spquery -v getRegularShowsInfo When now

EOT;

function my_seconds($n, $d=4) {
	if ( $n == 0 ) {
		return $n;
	} else {
		if ($n > 1) {
			$m = $n;
			$s = ' s';
			$e = max($d - 1 - floor(log($m,10)), 0);
		} elseif ($n > 0.001) {
			$m = 1000*$n;
			$s = ' ms';
			$e = min(max($d - 1 - floor(log($m,10)), 0), 3);
		} else {
			return round(1000000*$n) . ' μs';
		}
		return number_format($m, $e) . $s;
	}
}

$i = array_search('-v', $argv);
if ($i !== false) {
	unset($argv[$i]);
	$fn = 'var_dump';
} else {
	$fn = 'print_r';
}

if (count($argv) < 2) {
	print($usage);
	exit;
}

array_shift($argv);
$qp['method'] = array_shift($argv);
while (count($argv) > 1) {
	$qp[array_shift($argv)] = array_shift($argv);
}

if (!isset($mySpClientPath)
	|| !(include_once $mySpClientPath)
) {
	include_once 'SpinPapiClient.inc.php';
}

$sp = new SpinPapiClient($mySpUserID, $mySpSecret, $myStation, true);

if (isset($myFCache)) {
	$sp->fcInit($myFCache);
}
if (isset($myMemcache)) {
	$sp->mcInit($myMemcache);
}

$t0 = microtime(1);
$fn($sp->query($qp));
echo 'Query took: ' . my_seconds(microtime(1) - $t0) . PHP_EOL;

?>